---
- name: "Copy 'Virtual Hard Disks' directory from C: to N: on Windows Server"
  hosts: server2k25.reisingers.com
  gather_facts: false 
  vars:
    source_path: 'C:\ProgramData\Microsoft\Windows\Virtual Hard Disks'
    dest_path: 'N:\Virtual Hard Disks'
    
  tasks:
    - name: Ensure the destination directory exists (N:\Virtual Hard Disks)
      ansible.windows.win_file:
        path: "{{ dest_path }}"
        state: directory
        
    - name: Copy the source directory content to the destination (and overwrite)
      ansible.windows.win_copy:
        src: "{{ source_path }}"
        dest: "{{ dest_path }}"
        # Set `force: yes` to ensure the copy operation overwrites existing files/directories.
        force: yes
        # Set `remote_src: yes` because the source is already on the target server.
        remote_src: yes
