---
- name: Backup Hyper-V
  hosts: server2k25.reisingers.com
  gather_facts: no

  vars:
    source_path: "C:\\ProgramData\\Microsoft\\Windows\\Virtual Hard Disks"
    dest_path:   "N:\\Virtual Hard Disks"

  tasks:

    - name: Ensure destination folder exists
      win_file:
        path: "{{ dest_path }}"
        state: directory

    - name: Copy VHDX files using robocopy (with overwrite)
      win_command: >
        robocopy "{{ source_path }}" "{{ dest_path }}"
        /MIR /R:3 /W:5 /NFL /NDL /NP /TEE
      register: robocopy_result
      failed_when: robocopy_result.rc >= 8
      changed_when: robocopy_result.rc != 0

    - name: Show robocopy output
      debug:
        var: robocopy_result.stdout
