---
- name: Run Existing PowerShell Script on Remote Windows Server
  # Change 'windows_server' to the exact hostname you want to target.
  hosts: server2k19.reisingers.com # Targeted based on failure log
  gather_facts: no
  
  # Ensure Ansible is configured for Windows management (WinRM)
  vars:
    # UPDATED: Path to the .ps1 file already on the remote Windows server (using path from error log)
    remote_script_path: "C:\\ProgramData\\Paessler\\PRTG Network Monitor\\Configuration Auto-Backups\\PRTG_Backup.ps1" 
    
  tasks:
    # Removed win_copy task since the script already exists on the server.
    
    - name: Execute PowerShell script for network copy
      # win_shell is used to execute commands via the PowerShell shell on the Windows target.
      ansible.windows.win_shell: |
        # FINAL FIX: Use the call operator (&) with the path wrapped in single quotes ('') 
        # to prevent PowerShell from splitting the path at spaces.
        & '{{ remote_script_path }}'
        # If your script accepts parameters, pass them here: & '{{ remote_script_path }}' -Param Value
      args:
        # Explicitly use powershell.exe for execution
        executable: powershell.exe
      register: ps_output
      
    - name: Display PowerShell script output (optional)
      ansible.builtin.debug:
        var: ps_output.stdout_lines
