---
- name: Backup GitHub Repositories
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    backup_dest: "~/github-backups"
    repositories:
      - name: "semaphore"
        url: "git@github.com:kevinreisinger/semaphore.git"
      # Add more repos here

  tasks:
    - name: Ensure the backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dest }}"
        state: directory
        mode: '0755'

    - name: Clone repository (--mirror) if missing
      ansible.builtin.command:
        cmd: "git clone --mirror {{ item.url }} {{ backup_dest }}/{{ item.name }}.git"
      args:
        creates: "{{ backup_dest }}/{{ item.name }}.git"
      environment:
        # This forces SSH to ignore the "Unknown Host" prompt completely
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      loop: "{{ repositories }}"

    - name: Update repository if it already exists
      ansible.builtin.command:
        cmd: "git --git-dir={{ backup_dest }}/{{ item.name }}.git remote update"
      environment:
        # Also needed here for updates
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      loop: "{{ repositories }}"
      # Only run this task if the directory actually exists
      when: lookup('ansible.builtin.fileglob', backup_dest + '/' + item.name + '.git/HEAD') | length > 0
      ignore_errors: yes
