---
- name: Backup GitHub Repositories
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    backup_dest: "~/github-backups"
    repositories:
      - name: "semaphore"
        url: "git@github.com:kevinreisinger/semaphore.git"
      # Add more repos here

  tasks:
    - name: Ensure the backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dest }}"
        state: directory
        mode: '0755'

    - name: Clone repository (--mirror) if missing
      ansible.builtin.command:
        # --mirror includes all refs (branches, tags, notes)
        cmd: "git clone --mirror {{ item.url }} {{ backup_dest }}/{{ item.name }}.git"
      args:
        # This prevents the command from running if the folder already exists
        creates: "{{ backup_dest }}/{{ item.name }}.git"
      loop: "{{ repositories }}"

    - name: Update repository if it already exists
      ansible.builtin.command:
        # 'remote update' is the correct way to refresh a mirrored repo
        cmd: "git --git-dir={{ backup_dest }}/{{ item.name }}.git remote update"
      loop: "{{ repositories }}"
      # Only run this task if the directory actually exists (safety check)
      when: lookup('ansible.builtin.fileglob', backup_dest + '/' + item.name + '.git/HEAD') | length > 0 or true
      ignore_errors: yes
