---
- name: Backup HAOS Backups to Network Share
  hosts: server2k19.reisingers.com
  gather_facts: no

  vars:
    # NOTE: Adjust paths and credentials below
    source_share: '\\haos01\backup'
    destination_share: '\\kevireis-home\i$\Applications\Haos\Backup'
    share_username:
    share_password:
    max_backups_to_keep: 10

  tasks:
    - name: Copy HAOS backups via mapped drives and apply retention
      ansible.windows.win_powershell:
        parameters:
          source_share: "{{ source_share }}"
          destination_share: "{{ destination_share }}"
          share_username: "{{ share_username }}"
          share_password: "{{ share_password }}"
          max_backups_to_keep: "{{ max_backups_to_keep }}"
        script: |
          param(
            [string]$source_share,
            [string]$destination_share,
            [string]$share_username,
            [string]$share_password,
            [int]$max_backups_to_keep
          )

          $timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
          $log_dir = 'C:\Temp'
          if (-not (Test-Path $log_dir)) {
            New-Item -ItemType Directory -Path $log_dir | Out-Null
          }

          $robocopy_log = Join-Path $log_dir "HAOS_Backup_Copy_$timestamp.log"
          $robocopy_exit_code = 0

          Write-Host "=== Starting HAOS Backup Copy (Mapped Drive Method) ==="
          Write-Host "Source: $source_share"
          Write-Host "Destination: $destination_share"
          Write-Host "Log: $robocopy_log"

          $srcDrive = 'Z:'
          $dstDrive = 'Y:'

          # --- Step 1: Map drives ---
          try {
            Write-Host "Mapping network drives..."
            cmd.exe /c "net use $srcDrive $source_share /user:$share_username $share_password /persistent:no" | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "Failed to map source share." }

            cmd.exe /c "net use $dstDrive $destination_share /user:$share_username $share_password /persistent:no" | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "Failed to map destination share." }

            Write-Host "Successfully mapped $srcDrive -> $source_share and $dstDrive -> $destination_share"
          }
          catch {
            Write-Error "Network drive mapping failed: $($_.Exception.Message)"
            exit 1
          }

          # --- Step 2: Sanity check: confirm source files exist ---
          Write-Host "Verifying source drive visibility..."
          $srcTest = Get-ChildItem "$srcDrive\" -ErrorAction SilentlyContinue | Select-Object -First 3
          if (-not $srcTest) {
            Write-Error "Source directory appears empty or inaccessible ($source_share)."
            cmd.exe /c "net use $srcDrive /delete /Y" | Out-Null
            cmd.exe /c "net use $dstDrive /delete /Y" | Out-Null
            exit 1
          }

          # --- Step 3: Perform Robocopy ---
          Write-Host "Executing robocopy mirror from $srcDrive to $dstDrive..."
          robocopy "$srcDrive\" "$dstDrive\" /MIR /R:1 /W:3 /V /NP /LOG+:$robocopy_log
          $robocopy_exit_code = $LASTEXITCODE
          Write-Host "Robocopy finished with exit code $robocopy_exit_code."

          # --- Step 4: Retention Policy ---
          if ($robocopy_exit_code -le 7) {
            Write-Host "Applying retention policy (keep $max_backups_to_keep latest backups)..."
            try {
              $backups = Get-ChildItem "$dstDrive\" -Include *.tar, *.tar.gz, *.zip -File -Recurse | Sort-Object LastWriteTime -Descending
              if ($backups.Count -gt $max_backups_to_keep) {
                $toDelete = $backups | Select-Object -Skip $max_backups_to_keep
                foreach ($file in $toDelete) {
                  Write-Host "Deleting old backup: $($file.FullName)"
                  Remove-Item $file.FullName -Force -ErrorAction SilentlyContinue
                }
              }
            }
            catch {
              Write-Host "WARNING: Failed to apply retention policy. $($_.Exception.Message)"
            }
          }

          # --- Step 5: Cleanup ---
          Write-Host "Cleaning up mapped drives..."
          cmd.exe /c "net use $srcDrive /delete /Y" | Out-Null
          cmd.exe /c "net use $dstDrive /delete /Y" | Out-Null

          # --- Step 6: Diagnostics Dump ---
          $logContent = "Log not found."
          if (Test-Path $robocopy_log) {
            $logContent = (Get-Content $robocopy_log -ErrorAction SilentlyContinue | Out-String)
          }

          $diagnosticMessage = "--- TASK DIAGNOSTICS DUMP ---`n"
          $diagnosticMessage += "Robocopy Exit Code: $robocopy_exit_code`n"
          $diagnosticMessage += "ROBOCOPY LOG:`n$logContent`n--- END LOG ---"

          if ($robocopy_exit_code -le 7) {
            Write-Host "Backup copy completed successfully."
            Write-Host $diagnosticMessage
          } else {
            Write-Error "CRITICAL FAILURE: Robocopy exited with code $robocopy_exit_code.`n$diagnosticMessage"
            exit 1
          }
