---
- name: Rewritten Semaphore Project Backup to Windows Share
  # This playbook runs on the Ansible Controller/Semaphore Host.
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # --- SEMAPHORE API CONFIGURATION ---
    # SUCCESS: The path /api/project/{{ semaphore_project_id }}?export=true worked!
    semaphore_api_host: "http://ansible01.reisingers.com:3000"
    semaphore_api_token: "qw7gqe5cfbzykkzwt-iwoxshrw1yykpnen1jdnjduza="
    semaphore_project_id: 3

    # --- WINDOWS NETWORK SHARE CONFIGURATION ---
    # IMPORTANT: Ensure these variables are correctly set for the target share.
    smb_unc_path: "//kevireis-home/i$/Applications/Semaphore/Backup/Reisingers Project"
    share_username: ""
    share_password: "" # Use the correct variable name here for consistency

    # --- BACKUP FILE CONFIGURATION ---
    local_temp_dir: "/tmp/semaphore_db_export"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
    export_filename: "project_{{ semaphore_project_id }}_export_{{ timestamp }}.json"
    # Full local path for clarity
    local_export_path: "{{ local_temp_dir }}/{{ export_filename }}"

  tasks:
    - name: Setup Prerequisites and Environment
      block:
        - name: "Ensure smbclient is installed (REQUIRED FOR WINDOWS SHARE COPY)"
          ansible.builtin.package:
            name: smbclient
            state: present
          become: yes 

        - name: Ensure local temporary directory exists
          ansible.builtin.file:
            path: "{{ local_temp_dir }}"
            state: directory
            mode: '0755'

    - name: "Call Semaphore API to Export Project JSON (SUCCESSFUL PATH)"
      ansible.builtin.uri:
        # SUCCESSFUL PATH
        url: "{{ semaphore_api_host }}/api/project/{{ semaphore_project_id }}?export=true"
        method: GET
        headers:
          Authorization: "Bearer {{ semaphore_api_token }}"
        return_content: true
        validate_certs: true
      register: project_export_result

    - name: Process Exported Data and Backup to Share
      block:
        - name: Write the exported JSON content to a local temporary file (formatted)
          ansible.builtin.copy:
            content: "{{ project_export_result.content | from_json | to_nice_json }}"
            dest: "{{ local_export_path }}"
            mode: '0644'

        - name: Copy the exported JSON file to the Windows Network Share using smbclient
          # TEMPORARY FIX: no_log: true is removed so we can see the smbclient error output.
          # We need to see the output to diagnose the network/credential issue.
          ansible.builtin.shell: |
            smbclient "{{ smb_unc_path }}" -U "{{ share_username }}%{{ share_password }}" -c "put {{ local_export_path }} {{ export_filename }}"

        - name: Display Backup Status
          ansible.builtin.debug:
            msg: "✅ Semaphore Project DB (ID: {{ semaphore_project_id }}) successfully exported and copied to {{ smb_unc_path }}/{{ export_filename }}"

      # The 'always' section guarantees cleanup runs, even if the SMB copy fails.
      always:
        - name: Clean up local temporary JSON file
          ansible.builtin.file:
            path: "{{ local_export_path }}"
            state: absent
