---
- name: Backup GitHub Repositories (Readable Files) to SMB
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  vars:
    # --- CONFIGURATION ---
    local_data_path: "{{ ansible_user_dir }}/github-backups"
    
    # SMB Share Details
    smb_share_path: "//10.11.202.15/i$/Applications/Semaphore/Backup/Github"
    smb_username: "kevireis"
    smb_domain: "REISINGERS"
    # Hardcoded to empty string as requested
    share_password: ""
    smb_mount_point: "/mnt/temp_smb_backup"

    # Backup Naming
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"
    backup_filename: "github_backup_{{ timestamp }}.tar.gz"
    
    # Retention
    retention_days: 10

    # SSH Keys (Base64 Encoded Secret - lowercase variable name)
    ssh_key_content: "{{ lookup('env', 'github_ssh_key') | b64decode }}"
    key_path: "/tmp/github_deploy_key"

    # Repositories
    repositories:
      - name: "semaphore"
        url: "git@github.com:kevinreisinger/semaphore.git"

  tasks:
    # -------------------------------------------------------
    # 1. PREPARATION
    # -------------------------------------------------------
    - name: "CHECK: Is github_ssh_key set?"
      ansible.builtin.fail:
        msg: "CRITICAL ERROR: 'github_ssh_key' secret is missing."
      when: ssh_key_content | length == 0

    - name: Write Private Key to temp file
      ansible.builtin.copy:
        content: "{{ ssh_key_content }}"
        dest: "{{ key_path }}"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
      no_log: true

    - name: Ensure local backup directory exists
      ansible.builtin.file:
        path: "{{ local_data_path }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"

    - name: Ensure mount point directory exists
      ansible.builtin.file:
        path: "{{ smb_mount_point }}"
        state: directory
        mode: '0755'

    - name: Install CIFS Utils
      ansible.builtin.apt:
        name: cifs-utils
        state: present
        update_cache: yes
      ignore_errors: yes 

    # -------------------------------------------------------
    # 2. GIT CLONE (READABLE FILES)
    # -------------------------------------------------------
    - name: Clone repository (Standard Readable Format)
      ansible.builtin.command:
        cmd: "git clone {{ item.url }} {{ local_data_path }}/{{ item.name }}"
      args:
        creates: "{{ local_data_path }}/{{ item.name }}"
      become: yes
      become_user: "{{ ansible_user_id }}"
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ key_path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      loop: "{{ repositories }}"

    - name: Update repository (git pull) if it exists
      ansible.builtin.command:
        cmd: "git pull"
      args:
        chdir: "{{ local_data_path }}/{{ item.name }}"
      become: yes
      become_user: "{{ ansible_user_id }}"
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ key_path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      loop: "{{ repositories }}"
      when: (local_data_path + '/' + item.name) is directory
      ignore_errors: yes

    # -------------------------------------------------------
    # 3. COMPRESSION
    # -------------------------------------------------------
    - name: Compress backup directory
      community.general.archive:
        path: "{{ local_data_path }}"
        dest: "/tmp/{{ backup_filename }}"
        format: gz
      ignore_errors: yes
      register: archive_result

    - name: Compress via Shell (Fallback)
      ansible.builtin.command:
        cmd: "tar -czf /tmp/{{ backup_filename }} -C {{ ansible_user_dir }} github-backups"
      when: archive_result.failed is defined and archive_result.failed

    # -------------------------------------------------------
    # 4. MOUNT SMB & COPY
    # -------------------------------------------------------
    - name: Mount SMB Share
      ansible.posix.mount:
        src: "{{ smb_share_path }}"
        path: "{{ smb_mount_point }}"
        opts: "username={{ smb_username }},password={{ share_password }},domain={{ smb_domain }},vers=3.0,iocharset=utf8"
        fstype: cifs
        state: mounted

    - name: Copy backup to SMB share
      ansible.builtin.copy:
        src: "/tmp/{{ backup_filename }}"
        dest: "{{ smb_mount_point }}/{{ backup_filename }}"
        remote_src: yes

    # -------------------------------------------------------
    # 5. RETENTION POLICY
    # -------------------------------------------------------
    - name: Find backups older than {{ retention_days }} days
      ansible.builtin.find:
        paths: "{{ smb_mount_point }}"
        patterns: "github_backup_*.tar.gz"
        age: "{{ retention_days }}d"
        recurse: no
      register: old_backups

    - name: Delete old backups
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_backups.files }}"
      loop_control:
        label: "{{ item.path }}"

    # -------------------------------------------------------
    # 6. CLEANUP
    # -------------------------------------------------------
    - name: Unmount SMB Share
      ansible.posix.mount:
        path: "{{ smb_mount_point }}"
        state: unmounted

    - name: Remove temporary files and keys
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ key_path }}"
        - "/tmp/{{ backup_filename }}"
        - "{{ local_data_path }}"
      ignore_errors: yes

    - name: Display success message
      ansible.builtin.debug:
        msg: "Backup complete. {{ old_backups.matched }} old backups removed."
