---
- name: Rewritten Semaphore Project Backup to Windows Share
  # This playbook runs on the Ansible Controller/Semaphore Host.
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # --- SEMAPHORE API CONFIGURATION ---
    semaphore_api_host: "http://ansible01.reisingers.com:3000"
    semaphore_api_token: "qw7gqe5cfbzykkzwt-iwoxshrw1yykpnen1jdnjduza="
    semaphore_project_id: 3

    # --- WINDOWS NETWORK SHARE CONFIGURATION ---
    smb_share_name: "//kevireis-home/i$"
    smb_remote_path: "/Applications/Semaphore/Backup/Reisingers Project" # Subdirectory inside the share
    share_username: ""
    share_password: "" 

    # --- BACKUP FILE CONFIGURATION ---
    local_temp_dir: "/tmp/semaphore_db_export"
    temp_export_filename: "project_{{ semaphore_project_id }}_export_temp.json"
    local_temp_path: "{{ local_temp_dir }}/{{ temp_export_filename }}"
    
    # Final name includes timestamp, used only for the remote file
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
    final_remote_filename: "project_{{ semaphore_project_id }}_export_{{ timestamp }}.json"
    
    # Combined UNC Path for the final destination
    final_unc_path: "{{ smb_share_name }}{{ smb_remote_path }}"

  tasks:
    - name: Setup Prerequisites and Environment
      block:
        - name: "Ensure smbclient is installed (REQUIRED FOR WINDOWS SHARE COPY)"
          ansible.builtin.package:
            name: smbclient
            state: present
          become: yes 

        - name: Ensure local temporary directory exists
          ansible.builtin.file:
            path: "{{ local_temp_dir }}"
            state: directory
            mode: '0755'

    - name: "Call Semaphore API to Export Project JSON (ATTEMPT 9: GET /api/dump?project=ID)"
      ansible.builtin.uri:
        # FIX: Trying root-level API dump endpoint with ID as query parameter.
        url: "{{ semaphore_api_host }}/api/dump?project_id={{ semaphore_project_id }}"
        method: GET 
        headers:
          Authorization: "Bearer {{ semaphore_api_token }}"
        return_content: true
        validate_certs: true
      register: project_export_result

    - name: Process Exported Data and Backup to Share
      block:
        - name: Write the exported JSON content to a local temporary file (using fixed path)
          ansible.builtin.copy:
            content: "{{ project_export_result.content | from_json | to_nice_json }}"
            dest: "{{ local_temp_path }}"
            mode: '0644'

        - name: Copy the exported JSON file to the Windows Network Share using smbclient
          ansible.builtin.shell: |
            smbclient "{{ smb_share_name }}" -U "{{ share_username }}%{{ share_password }}" -c "put \"{{ local_temp_path }}\" \"{{ smb_remote_path }}/{{ final_remote_filename }}\""
          no_log: true 

        - name: Display Backup Status
          ansible.builtin.debug:
            msg: "✅ Semaphore Project DB (ID: {{ semaphore_project_id }}) successfully exported and copied to {{ final_unc_path }}/{{ final_remote_filename }}"

      # The 'always' section guarantees cleanup runs, even if the SMB copy fails.
      always:
        - name: Clean up local temporary JSON file
          ansible.builtin.file:
            path: "{{ local_temp_path }}"
            state: absent
