---
- name: Automated Jellyfin Backup and Network Transfer
  hosts: server2k19.reisingers.com
  # Removed become: true, become_method: runas, and become_user
  
  vars:
    # âš ï¸ NOTE: These values are used for the API call only.
    jellyfin_url: "http://server2k19.reisingers.com:8096"
    jellyfin_api_key: "ba76d7d9312744a89f6ba3ed85a20921"
    
    # Local Windows paths
    local_backup_path: "C:\\ProgramData\\Jellyfin\\Server\\data\\backups" 
    
    # Destination Network Share (UNC path)
    network_share_path: "\\\\kevireis-home\\i$\\Applications\\Jellyfin\\Backup"
    
    temp_zip_pattern: 'jellyfin-backup-*.zip'
    
  tasks:
    - name: ðŸ“ž Trigger Jellyfin Built-in Backup via API (Run on Controller)
      ansible.builtin.uri:
        url: "{{ jellyfin_url }}/Backup/Create"
        method: POST
        headers:
          X-MediaBrowser-Token: "{{ jellyfin_api_key }}"
          Content-Type: application/json
        body: '{"Metadata": true, "Trickplay": false, "Subtitles": false, "Database": true}'
        body_format: json
        status_code: 200
      register: backup_trigger_result
      # FIX: Delegate API call to Ansible controller
      delegate_to: localhost 

    - name: ðŸ” Find the newest backup file (wait up to 5 minutes for creation)
      ansible.windows.win_find:
        paths: "{{ local_backup_path }}"
        file_type: file
        pattern: "{{ temp_zip_pattern }}"
        sort_by: ctime
        sort_order: desc
      register: found_files
      # Check if the file exists AND if its creation time is recent
      until: found_files.files | length > 0 and (found_files.files[0].creation_time | to_datetime) > (ansible_date_time.epoch | int - 300) | to_datetime(format='%s')
      retries: 30 
      delay: 10   

    - name: ðŸ“ Set variable for the newest backup file
      ansible.builtin.set_fact:
        newest_backup_file: "{{ found_files.files[0].path }}"
        
    - name: ðŸ“¤ Copy the newest backup file to the network share
      # This task requires ansible_share_username/password to be set outside the playbook.
      ansible.windows.win_copy:
        src: "{{ newest_backup_file }}"
        dest: "{{ network_share_path }}"
        remote_src: true 

    - name: ðŸ§¹ Clean up old local backup files (keeping only the newest one)
      ansible.windows.win_find:
        paths: "{{ local_backup_path }}"
        file_type: file
        pattern: "{{ temp_zip_pattern }}"
        sort_by: ctime
        sort_order: desc
      register: all_local_backups

    - name: ðŸ—‘ï¸ Delete older local files (all except the first/newest file)
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ all_local_backups.files[1:] }}"
      when: all_local_backups.files | length > 1
      loop_control:
        label: "Deleting {{ item.path | split('\\') | last }}"
