---
- name: Execute HyperV Live Disk Backup via PowerShell VSS Script
  hosts: server2k25.reisingers.com
  gather_facts: false
  
  vars:
    target_volume: 'C' 
    source_dir: 'C:\ProgramData\Microsoft\Windows\Virtual Hard Disks'
    dest_dir: 'N:\Virtual Hard Disks'
    
  tasks:
    - name: Copy backup_hyperv.ps1 script to target server
      ansible.windows.win_copy:
        # Target your local script in the 'scripts' subdirectory
        src: ./scripts/backup_hyperv.ps1 
        dest: C:\Temp\backup_hyperv.ps1
        
    - name: Execute the VSS copy script and pass parameters
      ansible.windows.win_powershell:
        path: C:\Temp\backup_hyperv.ps1
        arguments: 
          - "-SourcePath '{{ source_dir }}'"
          - "-DestinationPath '{{ dest_dir }}'"
          - "-Volume '{{ target_volume }}'"
      register: script_output
      
    - name: Display script output (to confirm VSS success)
      ansible.builtin.debug:
        var: script_output.stdout_lines
