---
- name: Execute Remote HyperV VSS Backup Script
  hosts: server2k25.reisingers.com
  gather_facts: false
  
  vars:
    # Variables for the PowerShell script arguments
    target_volume: 'C' 
    source_dir: 'C:\ProgramData\Microsoft\Windows\Virtual Hard Disks'
    dest_dir: 'N:\Virtual Hard Disks'
    
    # Path where the script is located on the Windows server
    remote_script_path: 'C:\Windows\Scripts\backup_hyperv.ps1' 
    
  tasks:
    - name: 📁 Ensure the C:\Windows\Scripts directory exists
      ansible.windows.win_file:
        path: C:\Windows\Scripts
        state: directory
        
    - name: ⚙️ Execute the remote VSS copy script using win_shell
      ansible.windows.win_shell:
        # Construct the PowerShell command string to execute the script and pass args
        cmd: |
          & "{{ remote_script_path }}" `
          -SourcePath '{{ source_dir }}' `
          -DestinationPath '{{ dest_dir }}' `
          -Volume '{{ target_volume }}'
      register: script_output
      
    - name: 🖥️ Display script output
      ansible.builtin.debug:
        var: script_output.stdout_lines
