---
- name: Backup HAOS Backups to Network Share
  hosts: server2k19.reisingers.com
  gather_facts: no

  vars:
    # --- SOURCE AND DESTINATION ---
    source_share: "\\\\haos01\\backup"
    destination_share: "\\\\kevireis-home\\i$\\Applications\\Haos\\Backup"

    # --- NETWORK SHARE CREDENTIALS (FILL THESE IN) ---
    share_username: ""
    share_password: ""

    # --- Drive letter to use for temporary mapping (must be free) ---
    mapped_drive_letter_src: "X"
    mapped_drive_letter_dst: "Y"

    # --- Retention ---
    max_backups_to_keep: 10

  tasks:

    - name: Execute HAOS Network Copy Script (PowerShell)
      ansible.windows.win_powershell:
        script: |
          # --- Config pulled from Ansible vars ---
          $SourceShare = '{{ source_share }}'
          $DestinationShare = '{{ destination_share }}'
          $MappedSrc = '{{ mapped_drive_letter_src }}'
          $MappedDst = '{{ mapped_drive_letter_dst }}'
          $ShareUser = '{{ share_username }}'
          $SharePass = '{{ share_password }}'
          $MaxKeep = {{ max_backups_to_keep }}

          Write-Host "=== Starting HAOS backup copy process ==="

          # --- 1. Unmap existing drives silently ---
          cmd.exe /c net use ${MappedSrc}: /delete /y | Out-Null
          cmd.exe /c net use ${MappedDst}: /delete /y | Out-Null

          # --- 2. Map both network shares ---
          Write-Host "Mapping source: ${MappedSrc}: to $SourceShare ..."
          cmd.exe /c net use ${MappedSrc}: "$SourceShare" | Out-Null
          if ($LASTEXITCODE -ne 0) {
              Write-Host "ERROR: Failed to map source share."
              exit 1
          }

          Write-Host "Mapping destination: ${MappedDst}: to $DestinationShare ..."
          cmd.exe /c net use ${MappedDst}: "$DestinationShare" "$SharePass" /user:"$ShareUser" /persistent:no | Out-Null
          if ($LASTEXITCODE -ne 0) {
              Write-Host "ERROR: Failed to map destination share."
              cmd.exe /c net use ${MappedSrc}: /delete /y | Out-Null
              exit 1
          }

          Write-Host "Network shares mapped successfully."

          # --- 3. Copy files from source to destination ---
          Write-Host "Copying files from ${MappedSrc}: to ${MappedDst}: ..."
          try {
              robocopy "${MappedSrc}:\\" "${MappedDst}:\\" /E /COPYALL /R:1 /W:3 /NFL /NDL /NP /LOG+:C:\Temp\HAOS_Backup_Copy.log"
          } catch {
              Write-Host "ERROR: Copy failed. $($_.Exception.Message)"
              exit 1
          }

          # --- 4. Retention (keep only most recent $MaxKeep backups) ---
          Write-Host "Applying retention policy (keep last $MaxKeep)..."
          $backups = Get-ChildItem -Path "${MappedDst}:\\" -Recurse -Include "*.tar", "*.tar.gz", "*.zip" |
                      Sort-Object LastWriteTime -Descending

          if ($backups.Count -gt $MaxKeep) {
              $toDelete = $backups | Select-Object -Skip $MaxKeep
              foreach ($file in $toDelete) {
                  Write-Host "Deleting old backup: $($file.FullName)"
                  Remove-Item $file.FullName -Force -ErrorAction SilentlyContinue
              }
          }

          # --- 5. Cleanup mappings ---
          Write-Host "Cleaning up network drives..."
          cmd.exe /c net use ${MappedSrc}: /delete /y | Out-Null
          cmd.exe /c net use ${MappedDst}: /delete /y | Out-Null

          Write-Host "HAOS backup copy completed successfully."
      register: haos_backup_result

    - name: Display result
      debug:
        var: haos_backup_result.stdout_lines
