---
- name: Backup GitHub Repositories
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    backup_dest: "~/github-backups"
    # Read the environment variable
    raw_key_content: "{{ lookup('env', 'github_ssh_key') }}"
    key_path: "/tmp/github_deploy_key"
    repositories:
      - name: "semaphore"
        url: "git@github.com:kevinreisinger/semaphore.git"

  tasks:
    # --- SAFETY CHECKS ---
    - name: "CHECK: Is the GITHUB_SSH_KEY variable set?"
      ansible.builtin.fail:
        msg: >
          CRITICAL ERROR: The environment variable 'GITHUB_SSH_KEY' is empty!
          Please go to your Semaphore Job Settings -> Secrets/Env Vars
          and ensure the secret is mapped to this job.
      when: raw_key_content | length == 0

    - name: "CHECK: Write key and verify formatting"
      ansible.builtin.copy:
        # We decode the base64 string back into real text
        content: "{{ raw_key_content | b64decode }}"
        dest: "{{ key_path }}"
        mode: '0600'
      no_log: true 

    - name: Ensure backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dest }}"
        state: directory
        mode: '0755'

    - name: Clone repository (--mirror)
      ansible.builtin.command:
        cmd: "git clone --mirror {{ item.url }} {{ backup_dest }}/{{ item.name }}.git"
      args:
        creates: "{{ backup_dest }}/{{ item.name }}.git"
      environment:
        # Pointing to the validated key file
        GIT_SSH_COMMAND: "ssh -i {{ key_path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      loop: "{{ repositories }}"

    - name: Update repository if it exists
      ansible.builtin.command:
        cmd: "git --git-dir={{ backup_dest }}/{{ item.name }}.git remote update"
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ key_path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      loop: "{{ repositories }}"
      when: lookup('ansible.builtin.fileglob', backup_dest + '/' + item.name + '.git/HEAD') | length > 0
      ignore_errors: yes

    - name: Cleanup Private Key
      ansible.builtin.file:
        path: "{{ key_path }}"
        state: absent
      ignore_errors: yes
