---
- name: Automated Jellyfin Backup and Network Transfer
  hosts: jellyfin_windows_server # Your Windows server
  become: true
  vars:
    jellyfin_url: "http://192.168.1.100:8096"
    jellyfin_api_key: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6" # âš ï¸ REPLACE THIS
    
    # Default path for Windows Service Install (adjust if needed)
    local_backup_path: "C:\\ProgramData\\Jellyfin\\Server\\data\\backups" 
    
    # Destination Network Share (use a UNC path)
    network_share_path: "\\\\your-nas\\backups\\jellyfin" # âš ï¸ REPLACE THIS
    
    temp_zip_pattern: 'jellyfin-backup-*.zip'
    
  tasks:
    - name: ðŸ“ž Trigger Jellyfin Built-in Backup via API
      ansible.builtin.uri:
        url: "{{ jellyfin_url }}/Backup/Create"
        method: POST
        headers:
          X-MediaBrowser-Token: "{{ jellyfin_api_key }}"
          Content-Type: application/json
        # These are the default options for a full backup.
        body: '{"Metadata": true, "Trickplay": false, "Subtitles": false, "Database": true}'
        body_format: json
        status_code: 200
      register: backup_trigger_result
      
    - name: ðŸ” Find the newest backup file (wait up to 5 minutes for creation)
      ansible.windows.win_find:
        paths: "{{ local_backup_path }}"
        file_type: file
        pattern: "{{ temp_zip_pattern }}"
        # Sort by creation time (descending) to get the newest file first
        sort_by: ctime
        sort_order: desc
      register: found_files
      until: found_files.files | length > 0 and (found_files.files[0].creation_time | to_datetime) > (ansible_date_time.epoch | int - 300) | to_datetime(format='%s')
      retries: 30 # Retry 30 times
      delay: 10   # Wait 10 seconds between retries (5 minutes total)

    - name: ðŸ“ Set variable for the newest backup file
      ansible.builtin.set_fact:
        newest_backup_file: "{{ found_files.files[0].path }}"
        
    - name: ðŸ“¤ Copy the newest backup file to the network share
      ansible.windows.win_copy:
        src: "{{ newest_backup_file }}"
        dest: "{{ network_share_path }}"
        remote_src: true # Tells Ansible to copy a file from the remote host
        
    - name: ðŸ§¹ Clean up old local backup files (keeping only the newest one)
      ansible.windows.win_find:
        paths: "{{ local_backup_path }}"
        file_type: file
        pattern: "{{ temp_zip_pattern }}"
        sort_by: ctime
        sort_order: desc
      register: all_local_backups

    - name: ðŸ—‘ï¸ Delete older local files (all except the first/newest file)
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: absent
      # Skip the first item in the list (the newest one)
      loop: "{{ all_local_backups.files[1:] }}"
      when: all_local_backups.files | length > 1
      loop_control:
        label: "Deleting {{ item.path | split('\\') | last }}"
