---
- name: Check Active Directory Replication Status (using replsummary)
  # Target domain_controllers group
  hosts: domain_controllers
  gather_facts: no

  tasks:
    # 1. Execute repadmin /replsummary command once
    # This command reports on the entire forest, so it only needs to run on one DC.
    - name: Execute repadmin /replsummary command (Run Once)
      ansible.windows.win_shell: |
        # Use repadmin /replsummary to generate a high-level table summarizing replication status.
        # The /latency option is excellent for quickly identifying slow replication links.
        & repadmin /replsummary /latency
      register: replsummary_output
      run_once: true
      delegate_to: "{{ inventory_hostname }}"
      # Ignore non-zero return codes (rc=1) which are common for repadmin even on success.
      failed_when: false

    # 2. Display the consolidated replication summary
    - name: Display Consolidated Replication Summary
      ansible.builtin.debug:
        msg: |
          ======================================================================
          CONSOLIDATED ACTIVE DIRECTORY REPLICATION SUMMARY
          (Generated from {{ inventory_hostname }} using repadmin /replsummary /latency)
          ======================================================================
          
          {{ replsummary_output.stdout | default('Failed to run repadmin /replsummary or no output was returned.') }}

          ----------------------------------------------------------------------
          STATUS: Raw Execution Code: {{ replsummary_output.rc }}
          ----------------------------------------------------------------------
      # Only show the output if the command was executed (i.e., on the first host)
      when: replsummary_output is defined and replsummary_output.stdout is defined
