---
- name: Get Uptime for VMware ESXi Hosts
  # IMPORTANT: We set 'connection: local' here, and we reinforce this in 'vars'
  # to prevent SSH connection attempts which are failing due to protocol mismatch.
  hosts: esx
  gather_facts: no
  connection: local
  vars:
    # Reinforce the connection type to ensure Ansible does NOT use SSH
    ansible_connection: local
    # --- REQUIRED: Replace these with actual secrets or Ansible Vault variables ---
    # These variables need access to read host facts from the ESXi host or vCenter.
    vmware_user: "root"
    vmware_pass: "risman69"

  tasks:
    - name: Gather ESXi Host Facts (including system health info)
      community.vmware.vmware_host_facts:
        # NOTE: Removed 'gather_subset' as it is not supported in your version of the VMware collection.
        # The connection to the host is handled by the VMware module, 
        # which uses the API (HTTPS) based on the provided credentials.
        hostname: "{{ inventory_hostname }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_pass }}"
        validate_certs: false # Set to true if you are using trusted certificates
      register: host_facts

    - name: Calculate Uptime in Days and Hours
      ansible.builtin.set_fact:
        # The uptime is returned in seconds under host_facts.ansible_facts.host_summary.quickStats.uptime
        esxi_uptime_seconds: "{{ host_facts.ansible_facts.host_summary.quickStats.uptime }}"
        
        # Calculate days and remaining hours
        esxi_uptime_formatted: >-
          {% set seconds = host_facts.ansible_facts.host_summary.quickStats.uptime | int %}
          {% set days = (seconds // (60 * 60 * 24)) %}
          {% set hours = ((seconds % (60 * 60 * 24)) // (60 * 60)) %}
          {{ days }} days, {{ hours }} hours

    - name: Display ESXi Host Uptime
      ansible.builtin.debug:
        msg: "Server: {{ inventory_hostname }} | OS: VMware ESXi | Uptime: {{ esxi_uptime_formatted }}"
