---
- name: Universal File Creation Test
  hosts: all
  gather_facts: true

  tasks:
    - name: Set target directory for Windows
      set_fact:
        target_dir: "C:\\Temp"
      when: ansible_os_family == 'Windows'

    - name: Set target directory for Linux
      set_fact:
        target_dir: "/tmp"
      when: ansible_os_family != 'Windows'

    - name: Ensure directory exists (Windows)
      ansible.windows.win_file:
        path: "{{ target_dir }}"
        state: directory
      when: ansible_os_family == 'Windows'

    - name: Create the test file
      ansible.builtin.copy:
        content: "This file was created by Ansible on {{ inventory_hostname }} running {{ ansible_os_family }}."
        dest: "{{ target_dir }}/ansible_universal_copy.txt"
    
    - name: Verify Success
      debug:
        msg: "Success! File created at {{ target_dir }}/ansible_universal_copy.txt on {{ inventory_hostname }}"
