---
- name: Copy PuTTY.exe from network share with credentials
  hosts: windows
  gather_facts: no

  vars:
    remote_putty_path: "C:\\Windows\\putty.exe"
    network_share_root: "\\\\kevireis-home\\i$\\Applications\\Telnet Clients\\Putty\\v0.83"
    putty_file_name: "putty.exe"
    share_username:
    share_password:

  tasks:
    - name: "Map network drive Z:"
      win_shell: |
        $User = "{{ share_username }}"
        $Pass = ConvertTo-SecureString "{{ share_password }}" -AsPlainText -Force
        $Cred = New-Object System.Management.Automation.PSCredential($User,$Pass)
        New-PSDrive -Name Z -PSProvider FileSystem -Root "{{ network_share_root }}" -Credential $Cred -Persist
      args:
        executable: powershell

    - name: Copy PuTTY.exe from mapped drive
      win_copy:
        src: "Z:\\{{ putty_file_name }}"
        dest: "{{ remote_putty_path }}"
        remote_src: yes
        force: yes   # overwrite if exists

    - name: Remove mapped network drive
      win_shell: Remove-PSDrive -Name Z
      args:
        executable: powershell
