---
- name: Install 7-Zip
  hosts: windows
  gather_facts: no

  # --------------------------------------------------------------------------
  # 🎯 STEP 1: DEFINE APPLICATION-SPECIFIC VARIABLES
  # --------------------------------------------------------------------------
  vars:
    # 🌟 NEW VARIABLE: List of hosts (hostnames from inventory) to skip.
    # Add the exact hostnames of the servers you want to skip installation on here.
    skipped_hosts:
      - 'dc08.reisingers.com'
      - 'vmwvc1.reisingers.com'
            
    app_name: "7-Zip 25.01 (x64)"
    
    # UNC File Path
    share_unc_root: "\\\\kevireis-home\\i$"
    installer_relative_path: "Applications\\Utilities\\7-Zip\\v25.01\\Setup.msi"
    
    # CRITICAL: Product ID
    product_id: "{23170F69-40C1-2702-2501-000001000000}"

    # Credentials
    share_username: ""
    share_password: ""
    
    # Internal Path Variables
    installer_source_unc: "{{ share_unc_root }}\\{{ installer_relative_path }}"
    local_installer_path: 'C:\Windows\Temp\7zip_install.msi'
  # --------------------------------------------------------------------------

  tasks:
    # --------------------------------------------------------------------------
    # 🚫 GLOBAL SKIP CHECK
    # This check is applied to ALL tasks. It ensures the task is ONLY run if the
    # current inventory hostname ({{ inventory_hostname }}) is NOT in the
    # 'skipped_hosts' list.
    # --------------------------------------------------------------------------
    - name: "SKIP CHECK: Host is explicitly marked for skipping"
      ansible.builtin.debug:
        msg: "Skipping host {{ inventory_hostname }} as it is listed in 'skipped_hosts'."
      when: inventory_hostname in skipped_hosts

    # --------------------------------------------------------------------------
    # The 'when' condition below is applied to all subsequent tasks.
    # It checks: (host is NOT skipped) AND (original installation logic)
    # --------------------------------------------------------------------------
    - name: "0.1. CHECK if {{ app_name }} is already installed (IDEMPOTENCY CHECK)"
      ansible.windows.win_shell: |
        $AppID = '{{ product_id }}'
        
        # Check both 32-bit and 64-bit uninstall paths for the specific GUID key name
        $Installed = Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*, HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* -ErrorAction SilentlyContinue |
          Where-Object {$_.PSChildName -eq $AppID}
        
        # Output JSON for Ansible to set the fact
        if ($Installed) {
          Write-Output '{"installed": true}'
        } else {
          Write-Output '{"installed": false}'
        }
      register: app_check_result
      changed_when: false
      when: inventory_hostname not in skipped_hosts

    - name: "0.2. Set fact: App installation status"
      ansible.builtin.set_fact:
        app_is_installed: "{{ (app_check_result.stdout | from_json).installed | default(false) }}"
      when: inventory_hostname not in skipped_hosts

    - name: "1. ESTABLISH UNC Connection and COPY Installer to Local Temp Directory"
      ansible.windows.win_shell: |
        # Only runs if 7-Zip is NOT installed.
        $uncPath = '{{ installer_source_unc }}'
        $destPath = '{{ local_installer_path }}'
        $shareUser = '{{ share_username }}'
        $sharePass = '{{ share_password }}'
        
        # A. Establish UNC session (required for copy command to use credentials)
        Write-Host "Establishing UNC session to: {{ share_unc_root }}"
        cmd.exe /c "net use {{ share_unc_root }} $sharePass /user:$shareUser /persistent:no"
        if ($LASTEXITCODE -ne 0) { Write-Error "Failed to establish UNC connection."; exit 1 }

        # B. Copy the file using the full UNC path
        Write-Host "Copying installer from $uncPath to $destPath"
        cmd.exe /c "copy /Y $uncPath $destPath"
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to copy file using UNC path."
          cmd.exe /c "net use {{ share_unc_root }} /delete /y" | Out-Null
          exit 1
        }
        Write-Host "File copied successfully."
      
      no_log: true
      register: copy_result
      when: 
        - inventory_hostname not in skipped_hosts  # <<< Global Skip
        - not app_is_installed                   # <<< Original Logic

    - name: "2. INSTALL 7-Zip from Local Path"
      ansible.windows.win_shell: |
        Write-Host "Installing {{ app_name }} from LOCAL path: {{ local_installer_path }}"
        msiexec.exe /i "{{ local_installer_path }}" /qn /norestart
      register: install_result
      changed_when: true
      when: 
        - inventory_hostname not in skipped_hosts # <<< Global Skip
        - copy_result is succeeded
        - not app_is_installed                   # <<< Original Logic

    - name: 3. CLEANUP local installer file
      ansible.windows.win_file:
        path: "{{ local_installer_path }}"
        state: absent
      when: 
        - inventory_hostname not in skipped_hosts # <<< Global Skip
        - not app_is_installed                   # <<< Original Logic

    - name: 4. CLEANUP UNC connection
      ansible.windows.win_shell: cmd.exe /c "net use {{ share_unc_root }} /delete /y"
      ignore_errors: yes
      failed_when: false
      when: 
        - inventory_hostname not in skipped_hosts # <<< Global Skip
        - not app_is_installed                   # <<< Original Logic
      
    - name: Display installation status
      ansible.builtin.debug:
        msg: >
          {% if inventory_hostname in skipped_hosts %}
          🚫 SKIPPED: Host {{ inventory_hostname }} was explicitly marked to be skipped.
          {% elif app_is_installed %}
          ✅ SUCCESS: {{ app_name }} was already installed. Playbook reported changed=0.
          {% else %}
          ✅ SUCCESS: {{ app_name }} installation was attempted. Check if 'changed=1' reported success.
          {% endif %}
      changed_when: false


### Key Changes Made:

1.  **New Variable (`skipped_hosts`):** A list of hostnames to exclude is defined at the top of the `vars` section.
2.  **Global Condition (`when: inventory_hostname not in skipped_hosts`):** This condition is applied to all installation, copy, and cleanup tasks. It uses the magic variable `inventory_hostname` to check if the current server's name is in the list.
3.  **Explicit Skip Message:** I added a specific `debug` task at the start to clearly log when a host is being skipped, which helps with auditability.
4.  **Final Status Message:** The final `debug` task was updated to clearly state if the host was skipped, installed successfully, or already installed.
