---
- name: Install Speedtest
  hosts: windows
  gather_facts: no

  vars:
    speedtest_unc_path: "\\\\kevireis-home\\i$\\Applications\\Utilities\\Ookla\\Speedtest\\"
    share_username: yourusername
    share_password: yourpassword

  tasks:
    - name: Copy Speedtest files from UNC share to C:\Windows
      win_shell: |
        $User = '{{ share_username }}'
        $Pass = ConvertTo-SecureString '{{ share_password }}' -AsPlainText -Force
        $Cred = New-Object System.Management.Automation.PSCredential($User, $Pass)

        $Source = '{{ speedtest_unc_path }}'
        $Destination = 'C:\Windows\'

        Write-Host "Copying contents from $Source to $Destination..."

        # Map share temporarily
        net use \\kevireis-home\i$ $($Cred.GetNetworkCredential().Password) /user:$($Cred.UserName) /persistent:no | Out-Null

        # Copy only the contents (not the folder itself)
        Copy-Item -Path (Join-Path $Source '*') -Destination $Destination -Recurse -Force

        # Remove the mapping
        net use \\kevireis-home\i$ /delete | Out-Null

        Write-Host "Files copied successfully to $Destination"
      args:
        executable: powershell
