---
- name: Copy PuTTY.exe from Windows share to Windows hosts
  hosts: windows
  gather_facts: no

  vars:
    source_share: "\\\\kevireis-home\\i$\\Applications\\Telnet Clients\\Putty\\v0.83\\putty.exe"
    remote_putty_path: "C:\\Windows\\putty.exe"

  tasks:
    - name: Copy PuTTY.exe from network share (overwrite if exists)
      win_copy:
        src: "{{ source_share }}"
        dest: "{{ remote_putty_path }}"
        remote_src: yes   # important for UNC path
        force: yes        # overwrite if already exists
