---
- name: Install Speedtest
  hosts: windows
  gather_facts: no

  vars:
    speedtest_remote_path: "C:\\Windows\\Speedtest.exe"
    speedtest_unc_path: "\\\\kevireis-home\\i$\\Applications\\Utilities\\Ookla\\Speedtest\\Speedtest.exe"
    share_username: 
    share_password: 

  tasks:
    - name: "Copy Speedtest from UNC share using PowerShell"
      win_shell: |
        $User = "{{ share_username }}"
        $Pass = ConvertTo-SecureString "{{ share_password }}" -AsPlainText -Force
        $Cred = New-Object System.Management.Automation.PSCredential($User,$Pass)

        $Source = "{{ speedtest_unc_path }}"
        $Destination = "{{ speedtest_remote_path }}"

        # Map the share temporarily
        net use \\kevireis-home\i$ $($Cred.GetNetworkCredential().Password) /user:$($Cred.UserName) /persistent:no

        # Copy the file, overwrite if it exists
        Copy-Item -Path $Source -Destination $Destination -Force

        # Remove the mapping
        net use \\kevireis-home\i$ /delete
      args:
        executable: powershell
