---
- name: Install Speedtest
  hosts: windows
  gather_facts: no

  vars:
    speedtest_unc_path: "\\\\kevireis-home\\i$\\Applications\\Utilities\\Ookla\\Speedtest\\"
    share_username: 
    share_password: 

  tasks:
    - name: Copy all Speedtest files from network share to C:\Windows
      win_shell: |
        {% raw %}
        $User = "{{ share_username }}"
        $Pass = ConvertTo-SecureString "{{ share_password }}" -AsPlainText -Force
        $Cred = New-Object System.Management.Automation.PSCredential($User, $Pass)

        $Source = "{{ speedtest_unc_path }}"
        $Destination = "C:\Windows\"

        Write-Host "Mapping network share..."
        cmd /c 'net use \\\\kevireis-home\\i$ {{ share_password }} /user:{{ share_username }} /persistent:no' | Out-Null

        Write-Host "Copying all files from $Source to $Destination..."
        # Copy all files and folders from within Speedtest (not the folder itself)
        Copy-Item -Path (Join-Path $Source '*') -Destination $Destination -Recurse -Force -ErrorAction Stop

        Write-Host "Cleaning up network mapping..."
        cmd /c 'net use \\\\kevireis-home\\i$ /delete /y' | Out-Null

        Write-Host "✅ All Speedtest files successfully copied to $Destination"
        {% endraw %}
      args:
        executable: powershell
