---
- name: 1. Provision a New Windows VM on Proxmox VE
  hosts: pmve
  gather_facts: false
  vars:
    pve_user: ""
    pve_pass: ""
    win_password: ""

  tasks:

    - name: 1.1. Ensure Proxmox API is reachable
      uri:
        url: "https://{{ inventory_hostname }}/api2/json"
        user: "{{ pve_user }}"
        password: "{{ pve_pass }}"
        method: GET
        validate_certs: no
      register: proxmox_api
      retries: 3
      delay: 10
      until: proxmox_api.status == 200

    - name: 1.2. Clone the Windows template and configure VM resources
      community.proxmox.proxmox_kvm:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ inventory_hostname }}"
        node: "pve"  # Adjust if your Proxmox node has a different name
        vmid: 200
        name: "win-vm-{{ inventory_hostname }}"
        template: "win-template"
        cores: 2
        memory: 4096
        netif:
          - model: virtio
            bridge: vmbr0
        boot: "cdn"
        state: present

    - name: 2.1. Join VM to domain
      microsoft.ad.membership:
        hostname: "{{ inventory_hostname }}"
        username: "Administrator"
        password: "{{ win_password }}"
        domain_name: "reisingers.com"
        state: domain
