- name: 1. Provision a New Windows VM on Proxmox VE
  hosts: pmve
  gather_facts: no
  connection: local

  vars:
    pve_host: "10.11.202.41"
    pve_user: ""        # e.g., ansible@pve
    pve_pass: ""
    pve_node: "pmve02"

    vm_id: 101
    vm_name: "kevireis-dload"
    template_id: 100
    ip_address_cidr: "10.11.202.14/24"
    gateway: "10.11.202.1"
    dns_servers: ["10.11.202.25","10.11.202.30","75.75.75.75"]

    win_user: "Administrator"
    win_password: "SecurePassword456"

  tasks:
    - name: 1.1. Ensure Proxmox is reachable
      ansible.builtin.wait_for:
        host: "{{ pve_host }}"
        port: 8006
        timeout: 30
      delegate_to: localhost

    - name: 1.2. Clone Windows template and configure VM
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_host }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        validate_certs: false
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        clone: "{{ template_id }}"
        full: true
        state: present
        cores: 2
        memory: 8192
        scsihw: virtio-scsi-pci
        net0: "virtio,bridge=vmbr0"
        ide2: "local:cloudinit"
        agent: 1
        # Cloud-Init configuration for Windows static IP + DNS + WinRM
        ciuser: "{{ win_user }}"
        cipassword: "{{ win_password }}"
        ipconfig0: >
          ip={{ ip_address_cidr | split('/')[0] }},
          gw={{ gateway }}
        nameserver: "{{ dns_servers | join(',') }}"
        winrm: true
        winrm_port: 5986
        winrm_scheme: https
      register: vm_creation_output
      environment:
        PYTHONPATH: "/usr/lib/python3/dist-packages"

    - name: 1.3. Start the new VM
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_host }}"
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        validate_certs: false
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        state: started
      environment:
        PYTHONPATH: "/usr/lib/python3/dist-packages"

    - name: 1.4. Wait for WinRM to become available
      ansible.builtin.wait_for_connection:
        timeout: 600
        delay: 30
      delegate_to: localhost
      vars:
        ansible_host: "{{ ip_address_cidr | split('/') | first }}"
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: basic
        ansible_user: "{{ win_user }}"
        ansible_password: "{{ win_password }}"

    - name: 1.5. Add new VM to dynamic inventory
      ansible.builtin.add_host:
        name: "{{ vm_name }}"
        groups: newly_provisioned_windows
        ansible_host: "{{ ip_address_cidr | split('/') | first }}"
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: basic
        ansible_user: "{{ win_user }}"
        ansible_password: "{{ win_password }}"
      delegate_to: localhost
