---
# ==============================================================================
# PLAY 1: PROVISIONING (Runs on the Proxmox host 'pmve')
# ==============================================================================
- name: ☁️ Provision a New Windows VM on Proxmox VE
  hosts: pmve
  gather_facts: false
  
  # CRITICAL FIX: Explicitly setting the collection path. Adjust this to the actual
  # location where you installed the collections.
  environment:
    ANSIBLE_COLLECTIONS_PATHS: "/usr/share/ansible/collections:/root/.ansible/collections" 
  
  vars:
    # --- Credentials (Ensure these are passed in via Vault or Semaphore) ---
    pve_user: ""
    pve_pass: ""
    win_password: ""
    domain_user: ""
    
    # --- VM Configuration ---
    vm_template_vmid: "100"
    vm_new_vmid: "101"
    vm_name: "kevireis-dload"
    vm_node: "pmve02"
    vm_storage: "pmvenfs"
    vm_memory: 8192
    vm_cores: 4
    vm_disk_size: 100G
    
    # --- Static Networking ---
    vm_ip: "10.11.202.14"
    vm_netmask: 24
    vm_gateway: "10.11.202.1"
    vm_dns: "10.11.202.25 10.11.202.30 75.75.75.75"

  tasks:
    # ----------------------------------------------------
    # 🔎 DEBUG TASKS (Temporary - Remove after success)
    # **FIXED: Task name is now wrapped in single quotes.**
    # ----------------------------------------------------
    - name: '⚙️ DEBUG: Show ANSIBLE_COLLECTIONS_PATHS environment variable'
      ansible.builtin.debug:
        var: lookup('env', 'ANSIBLE_COLLECTIONS_PATHS')
      delegate_to: localhost

    - name: '🔍 DEBUG: Show configured Ansible Collection Paths (via ansible-config)'
      ansible.builtin.shell: |
        ansible-config dump | grep COLLECTIONS_PATHS
      register: path_dump
      delegate_to: localhost

    - name: '💡 DEBUG: Display configured Paths'
      ansible.builtin.debug:
        var: path_dump.stdout_lines
      delegate_to: localhost
    # ----------------------------------------------------

    - name: 🎯 Ensure Proxmox API is reachable
      community.general.uri:
        url: "https://{{ inventory_hostname }}:8006/api2/json/nodes"
        user: "{{ pve_user }}"
        password: "{{ pve_pass }}"
        method: GET
        validate_certs: no
      register: proxmox_api
      retries: 5
      delay: 10
      until: proxmox_api.status == 200

    - name: 💾 Clone Windows template and configure VM resources
      community.proxmox.proxmox_vm:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_pass }}"
        api_host: "{{ inventory_hostname }}"
        vmid: "{{ vm_new_vmid }}"
        name: "{{ vm_name }}"
        clone: "{{ vm_template_vmid }}"
        full: true
        cores: "{{ vm_cores }}"
        memory: "{{ vm_memory }}"
        disk: "{{ vm_disk_size }}"
        node: "{{ vm_node }}"
        storage: "{{ vm_storage }}"
        timeout: 30
      delegate_to: localhost

    - name: ➕ Add new Windows VM to in-memory inventory for WinRM
      ansible.builtin.add_host:
        name: "{{ vm_name }}"
        groups: 'new_windows_vms'
        ansible_host: "{{ vm_ip }}"
        ansible_user: "{{ domain_user }}"
        ansible_password: "{{ win_password }}"
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_transport: basic
      delegate_to: localhost
      
# ==============================================================================
# PLAY 2: CONFIGURATION (Runs on the newly created Windows VM)
# ==============================================================================
- name: ⚙️ Configure the newly provisioned Windows VM
  hosts: new_windows_vms
  gather_facts: false 

  tasks:
    - name: ⏳ Wait for Windows VM to respond to WinRM
      ansible.windows.win_ping:
      register: winrm_check
      retries: 15
      delay: 20
      until: winrm_check.ping == "pong"
    
    - name: 🌐 Configure static IP networking
      ansible.windows.win_shell: |
        $Interface = Get-NetAdapter | Where-Object {$_.Status -eq "Up"} | Select-Object -First 1
        New-NetIPAddress -InterfaceAlias $Interface.Name -IPAddress "{{ vm_ip }}" -PrefixLength {{ vm_netmask }} -DefaultGateway "{{ vm_gateway }}"
        Set-DnsClientServerAddress -InterfaceAlias $Interface.Name -ServerAddresses "{{ vm_dns }}"
      when: vm_ip | length > 0

    - name: 📁 Create Temp directory on Windows VM
      ansible.windows.win_shell: |
        New-Item -Path "C:\Temp" -ItemType Directory -Force
