---
- name: Windows Updates with Auto Reboot
  hosts: all
  gather_facts: no
  vars:
    skip_reboot_servers:
      - dc08.reisingers.com
      # Add more servers here
    temp_summary_dir: "C:\\Temp"

  tasks:

    - name: Install all available updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Definition Updates
          - Drivers
          - Windows Defender
          - FeaturePacks
          - ServicePacks
          - Tools
          - Updates
        reboot: no
      register: update_result

    - name: Create per-host update summary file
      win_shell: |
        $Timestamp = (Get-Date).ToString("yyyy-MM-dd_HH-mm-ss")
        $SummaryPath = Join-Path "{{ temp_summary_dir }}" "windows_update_summary_$Timestamp.txt"
        New-Item -ItemType Directory -Force -Path "{{ temp_summary_dir }}" | Out-Null

        "Windows Update Summary for $env:COMPUTERNAME" | Out-File -FilePath $SummaryPath
        "" | Out-File -FilePath $SummaryPath -Append

        "Installed updates:" | Out-File -FilePath $SummaryPath -Append
        $updates = {{ update_result.updates | to_json | quote }} | ConvertFrom-Json
        foreach ($id in $updates.PSObject.Properties.Name) {
            $u = $updates.$id
            if ($u.installed -eq $true) {
                $kb = if ($u.kb) { "($($u.kb -join ', '))" } else { "" }
                "✅ $($u.title) $kb" | Out-File -FilePath $SummaryPath -Append
            }
        }

        "" | Out-File -FilePath $SummaryPath -Append
        "Failed updates:" | Out-File -FilePath $SummaryPath -Append
        foreach ($id in $updates.PSObject.Properties.Name) {
            $u = $updates.$id
            if ($u.installed -ne $true) {
                $kb = if ($u.kb) { "($($u.kb -join ', '))" } else { "" }
                "❌ $($u.title) $kb" | Out-File -FilePath $SummaryPath -Append
            }
        }

        "" | Out-File -FilePath $SummaryPath -Append

        $SkipReboot = @({{ skip_reboot_servers | map('quote') | join(', ') }})
        if ($SkipReboot -contains "{{ inventory_hostname }}") {
            if ({{ update_result.reboot_required | lower }}) {
                "⚠️ Reboot skipped (skip_reboot_servers)" | Out-File -FilePath $SummaryPath -Append
            } else {
                "✅ No reboot needed." | Out-File -FilePath $SummaryPath -Append
            }
        } else {
            if ({{ update_result.reboot_required | lower }}) {
                "⚠️ System will reboot automatically." | Out-File -FilePath $SummaryPath -Append
            } else {
                "✅ No reboot needed." | Out-File -FilePath $SummaryPath -Append
            }
        }

        $SummaryPath.Trim()
      args:
        executable: powershell
      register: host_summary_path

    - name: Reboot if required (skip_reboot_servers excluded)
      win_reboot:
      when:
        - update_result.reboot_required
        - inventory_hostname not in skip_reboot_servers
