---
- name: Windows Updates with Auto Reboot
  hosts: windows
  gather_facts: yes
  vars:
    temp_summary: "C:\\Temp\\windows_update_summary.txt"

  tasks:
    - name: Ensure Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - block:
        - name: Run Windows Updates (auto reboot if required)
          ansible.windows.win_updates:
            category_names:
              - SecurityUpdates
              - CriticalUpdates
              - Definition Updates
              - Windows Defender
              - Drivers
              - UpdateRollups
            reboot: yes
          register: update_result

      rescue:
        - name: Set empty update_result on failure
          ansible.builtin.set_fact:
            update_result:
              updates: {}
              failed_update_count: 0
              reboot_required: false

        - name: Debug Windows Update failure
          ansible.builtin.debug:
            msg: "Windows Update task failed (likely Task Scheduler issue). Continuing playbook."

    - name: Build summary file on Windows
      ansible.windows.win_shell: |
        $SummaryPath = "{{ temp_summary }}"
        "Windows Update Summary for {{ ansible_hostname }}" | Out-File -FilePath $SummaryPath
        "" | Out-File -FilePath $SummaryPath -Append
        "Installed updates:" | Out-File -FilePath $SummaryPath -Append
        foreach ($u in {{ update_result.updates | to_json | from_json }}.GetEnumerator()) {
          if ($u.Value.installed -eq $true) {
            " - $($u.Value.title) ($($u.Value.kb -join ', '))" | Out-File -FilePath $SummaryPath -Append
          }
        }
        "" | Out-File -FilePath $SummaryPath -Append
        "Failed updates:" | Out-File -FilePath $SummaryPath -Append
        foreach ($u in {{ update_result.updates | to_json | from_json }}.GetEnumerator()) {
          if ($u.Value.installed -ne $true) {
            " - $($u.Value.title) ($($u.Value.kb -join ', '))" | Out-File -FilePath $SummaryPath -Append
          }
        }
        "" | Out-File -FilePath $SummaryPath -Append
        "Reboot required: {{ update_result.reboot_required | default(false) }}" | Out-File -FilePath $SummaryPath -Append
      args:
        executable: powershell

    - name: Display summary info
      ansible.builtin.debug:
        msg:
          - "Installed updates: {{ update_result.installed_update_count | default(0) }}"
          - "Failed updates: {{ update_result.failed_update_count | default(0) }}"
          - "Reboot required: {{ update_result.reboot_required | default(false) }}"
