---
- name: Update Linux Servers
  hosts: linux
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 0

    - name: Upgrade all packages without reboot
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        purge: yes

    - name: Force upgrade deferred/systemd packages
      ansible.builtin.apt:
        name:
          - libnss-systemd
          - libpam-systemd
          - libsystemd-shared
          - libsystemd0
          - libudev1
          - snapd
          - systemd
          - systemd-dev
          - systemd-hwe-hwdb
          - systemd-resolved
          - systemd-sysv
          - systemd-timesyncd
          - tcpdump
        state: latest

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

#   - name: Notify via email if reboot is required
#     ansible.builtin.shell: |
#       echo "Updates installed on {{ inventory_hostname }} require a reboot." | mail -s "Reboot Required on {{ inventory_hostname }}" youremail@example.com
#     when: reboot_required.stat.exists
