---
- name: Update Linux Servers
  hosts: linux
  become: yes
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages, including phased/systemd packages
      ansible.builtin.apt:
        upgrade: dist
        allow_unauthenticated: no

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
